//import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Components/Header'
import Footer from './Components/Footer'
import {Red_Hat_Display} from'next/font/google'

const red_hat = Red_Hat_Display({
  weight: ['400', '700'],
  subsets: ['latin'],
})

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Midu Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={red_hat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
